### ISSUE TITLE
Entire game folder gets deleted upon auto-update

### ISSUE THREAD

**Issue by EdW0ke** [Inferno214221/cmc-mod-manager#1]
As title says, once the program says there's a beta available, and me having the CMC Mod Manager in the same folder as the game, the moment it updates, any other file that is not of CMCMM gets deleted.

**Comment by Inferno214221** [comment]
Hi,
Sorry if this caused you any loss of game data, however, the program is behaving as intended. CMC Mod Manager should not be placed directly in your CMC directory (hence the requirement to select your directory within the program) and should be located in an entirely seperate location or at least within a dedicated mod manager folder within your build.
Although the program is working as intended, I will update it to clarify and warn the user if the program is located within the same directory, as this is not the first time this mistake has been made.
