### ISSUE TITLE
Error when I install characters

### ISSUE THREAD

**Issue by GoofyDoofd** [Inferno214221/cmc-mod-manager#2]
every time when I install .rar characters with cmc mod manager this error keeps on saying:Error: ENOENT: no such file or directory, scandir 'C:\Users\elija\AppData\Local\Temp\cmc-mod-manager\487410_1718636200268_download', and it doesnt install the characters. Can you fix this please?

![bandicam 2024-06-17 16-25-34-485](https://github.com/Inferno214221/cmc-mod-manager/assets/173090045/afb485ca-f206-4270-97e2-08fe4d490c37)

**Comment by Inferno214221** [comment]
Hi,
Thanks for creating an issue, I believe I know what I did wrong, I'll look into this and fix it in the next release.
Thanks

**Comment by Inferno214221** [comment]
Fixed in v3.0.0-beta.3.

**Comment by Inferno214221** [comment]
Fixed in v3.0.0-beta.3.
