### ISSUE TITLE
Incorrect Dialog Height

### ISSUE THREAD

**Issue by PGames09** [Inferno214221/cmc-mod-manager#4]
![imagen](https://github.com/Inferno214221/cmc-mod-manager/assets/121964476/c63fbf50-ea89-4467-95ca-109637f8d39a)
![imagen](https://github.com/Inferno214221/cmc-mod-manager/assets/121964476/877d6dc1-0c96-42f0-ae36-eaba917ef798)

**Comment by PGames09** [comment]
![imagen](https://github.com/Inferno214221/cmc-mod-manager/assets/121964476/df70fb90-f8c0-4d20-a42d-498e49f9e16c)

**Comment by Inferno214221** [comment]
Ok, I've finally managed to replicate this issue. I believe it is the result of a race condition when trying to pass information to the window after the HTML before the React process has rendered and made its stateful declarations.

**Comment by PGames09** [comment]
Thanks @Inferno214221

**Comment by Inferno214221** [comment]
See #13. This bug is occurring once again, although less severe.
Given that this has been a reoccurring issue, it might make sense to just allow the user to re-size dialog windows.

**Comment by Inferno214221** [comment]
I know I just recommended against using auto, however there is a possibility that this issue is now fixed in [this release](https://github.com/Inferno214221/cmc-mod-manager/releases/tag/auto). @PGames09 is there any chance you could try that version and let me know if the issue still occurs?

**Comment by PGames09** [comment]
> I know I just recommended against using auto, however there is a possibility that this issue is now fixed in [this release](https://github.com/Inferno214221/cmc-mod-manager/releases/tag/auto). @PGames09 is there any chance you could try that version and let me know if the issue still occurs?

hi, i tried the new and latest verion and now it works!
it still appears cut off but I just resize the windows and the process works normally, thanks.

**Comment by Inferno214221** [comment]
In addition to the fixes (which obviously didn't work properly), I just allowed users to resize the window.
Given that this is working for most other users, I might just leave it as it is now, with the option for users to manually resize the window if it's not working.
